- name: Create directory
  ansible.builtin.file:
    path: /tmp/static-folder
    state: directory

- name: Create file
  ansible.builtin.file:
    path: /tmp/static-folder/file.json
    state: touch

- name: Delete file
  ansible.builtin.file:
    path: /tmp/static-folder/file.txt
    state: absent
