- name: Example Playbook
  hosts: all
  gather_facts: no
  tasks:
    - name: Task 1
      ansible.builtin.debug:
        msg: "This is Task 1"
      loop:
        - 1
        - 2
      tags:
        - task1
        - install

    - name: Task 2
      ansible.builtin.debug:
        msg: "This is Task 2"
      tags:
        - task2
        - install

    - name: Task 3
      ansible.builtin.debug:
        msg: "This is Task 3"
      tags:
        - task3

    - name: Task 4
      ansible.builtin.debug:
        msg: "This is Task 4"
      tags:
        - task4
