- name: Using vaults
  hosts: db
  gather_facts: no
  tasks:
    - name: Copy encrypted file
      ansible.builtin.copy:
        src: confidential_data.txt
        dest: /tmp/confidential_data.txt

    - name: Display file contents
      ansible.builtin.command: cat /tmp/confidential_data.txt
      register: command_output

    - name: Print to console
      ansible.builtin.debug:
        msg: "{{command_output.stdout}}"


