---
- name: Uninstall Nginx
  hosts: webserver
  become: true
  vars:
    nginx_version: "1.18.*"  # Specify the Nginx version here

  tasks:
    - name: Uninstall Nginx
      ansible.builtin.apt:
        name: "nginx={{ nginx_version }}"
        state: absent
