- name: Error handling using handlers
  hosts: all
  gather_facts: no
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
  tasks:
    - ansible.builtin.apt:
        name: some_unknown_package
        state: present
      ignore_errors: yes
      #ignore_unreachable: yes
    
    - name: Add random data to a file
      ansible.builtin.shell: head -c 1M </dev/urandom >> "/tmp/tmpfile_{{ date }}"
      when: "'002' in inventory_hostname"
    
    - name: Check file size
      ansible.builtin.stat:
        path: "/tmp/tmpfile_{{ date }}"
      register: result
      any_errors_fatal: true
      failed_when: 
        - result.stat.exists
        - result.stat.size > 3000000

    - name: Ping hosts
      ansible.builtin.ping:
