- name: Example playbook with conditionals
  hosts: all
  gather_facts: true
  vars:
    package: nginx
    state: present

  tasks:
    - name: Install nginx - Rocky
      become: true
      ansible.builtin.yum:
        name: "{{ package }}"
        state: "{{ state }}"
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Install nginx - Debian
      become: true
      ansible.builtin.apt:
        name: "{{ package }}"
        state: "{{ state }}"
      when: ansible_os_family == 'Debian'

    - name: Check if file exists
      ansible.builtin.stat:
        path: /tmp/file.txt
      register: file_stat

    - name: Print message if file exists
      ansible.builtin.debug:
        msg: "File exists!"
      when: file_stat.stat.exists

    - name: Create file if it does not exist
      ansible.builtin.file:
        path: /tmp/file.txt
        state: touch
      when: not file_stat.stat.exists
